version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: dittofeed-postgres
    environment:
      POSTGRES_USER: dittofeed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dittofeed
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dittofeed"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: dittofeed-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    container_name: dittofeed-clickhouse
    environment:
      CLICKHOUSE_DB: dittofeed
      CLICKHOUSE_USER: dittofeed
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.22
    container_name: dittofeed-temporal
    depends_on:
      - postgres
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=dittofeed
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgres
    ports:
      - "7234:7233"
    healthcheck:
      test: ["CMD", "temporal", "workflow", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  clickhouse_data:
