databases:
  - name: dittofeed-db

services:
  - type: worker
    name: dittofeed-workspace-worker
    runtime: image
    autoDeploy: false
    image:
      url: "dittofeed/dittofeed-worker:v0.23.0-alpha.41"
    dockerCommand: node --max-old-space-size=724 packages/lite/dist/scripts/startLite.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLICKHOUSE_PROTOCOL
        value: http
      - key: DASHBOARD_URL
        sync: false
      - key: REUSE_CONTEXT
        value: "true"
      - key: MAX_CACHED_WORKFLOWS
        value: "10"
      - key: TASK_QUEUE
        value: "workspace"
      - key: GLOBAL_CRON_TASK_QUEUE
        value: "workspace"
      - key: COMPUTED_PROPERTIES_TASK_QUEUE
        value: "workspace"
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: CLICKHOUSE_HOST
        sync: false
      - key: TEMPORAL_ADDRESS
        sync: false
      - key: PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CLICKHOUSE_USER
        value: dittofeed
      - key: CLICKHOUSE_PASSWORD
        sync: false 
