# A definitive render.yaml blueprint for deploying a single-node Redpanda instance on Render.com.
# This configuration exposes the Pandaproxy (HTTP) API to the internet and the native Kafka API
# to the private network. This is configured for production mode.

services:
  - type: web
    name: redpanda
    runtime: image
    image:
      url: docker.redpanda.com/redpandadata/redpanda:latest
    plan: standard
    region: oregon
    dockerCommand: "rpk redpanda start --smp 1 --memory 1536M --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:9093 --advertise-kafka-addr internal://${RENDER_INTERNAL_HOSTNAME}:9092,external://${RENDER_EXTERNAL_HOSTNAME}:9093 --pandaproxy-addr external://0.0.0.0:8082 --advertise-pandaproxy-addr external://${RENDER_EXTERNAL_HOSTNAME}:8082 --schema-registry-addr external_sr://0.0.0.0:8081 --rpc-addr 0.0.0.0:33145 --advertise-rpc-addr ${RENDER_INTERNAL_HOSTNAME}:33145 --set redpanda.enable_sasl=true --set redpanda.superusers=[\"dittofeed\"] --overprovisioned=false"
    envVars:
      - key: PORT
        value: "8082"
      - key: USER
        value: dittofeed
      - key: PASSWORD
        sync: false

    disk:
      name: redpanda-data
      mountPath: /var/lib/redpanda/data
      sizeGB: 10

    healthCheckPath: /status/ready
