# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
# $schema: https://render.com/schema/render.yaml.json

databases:
  - name: dittofeed-db

envVarGroups:
  - name: clickhouse-credentials
    envVars:
      - key: CLICKHOUSE_USER
        value: dittofeed
      - key: CLICKHOUSE_PASSWORD
        generateValue: true
  - name: backend-app-env
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLICKHOUSE_PROTOCOL
        value: http
      - key: DASHBOARD_URL_NAME
        value: RENDER_EXTERNAL_URL
      - key: DASHBOARD_API_NAME
        value: RENDER_EXTERNAL_URL
      - key: DASHBOARD_API_DOMAIN
        value: onrender.com
      - key: DASHBOARD_API_PORT
        value: 443
      - key: LITE_MEM_LIMIT
        value: 412
services:
  - type: web
    name: dittofeed-ee
    runtime: image
    autoDeploy: false
    image:
      url: "docker.io/dittofeed/dittofeed-ee:v0.22.0-ee.6"
      creds:
        fromRegistryCreds:
          name: dittofeed
    # Setting Node.js max-old-space-size to 412 MB.
    # This is calculated as follows: Total RAM (512 MB) - Buffer (100 MB) -
    # Memory for other processes (100 MB).
    dockerCommand: node --max-old-space-size=412 ./packages/ee/dist/scripts/startLite.js
    envVars:
      - fromGroup: backend-app-env
      - fromGroup: clickhouse-credentials
      - key: REUSE_CONTEXT
        value: "true"
      - key: MAX_CACHED_WORKFLOWS
        value: "10"
      - key: DATABASE_HOST
        fromDatabase:
          name: dittofeed-db
          property: host
      - key: DATABASE_USER
        fromDatabase:
          name: dittofeed-db
          property: user
      - key: DATABASE_PORT
        fromDatabase:
          name: dittofeed-db
          property: port
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: dittofeed-db
          property: password
      - key: CLICKHOUSE_HOST
        fromService:
          type: pserv
          name: dittofeed-ch
          property: host
      - key: TEMPORAL_ADDRESS
        fromService:
          type: pserv
          name: temporal
          property: host
      - key: AUTH_MODE
        value: "multi-tenant"
      - key: AUTH_PROVIDER
        value: "auth0"
      - key: SIGNOUT_URL
        value: "/dashboard/signout"
      - key: OPEN_ID_CLIENT_ID
        sync: false
      - key: OPEN_ID_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      # comment out bootstrap env var after initial setup
      - key: BOOTSTRAP
        value: "true"
  - type: pserv
    name: dittofeed-ch
    env: docker
    plan: standard
    autoDeploy: false
    dockerfilePath: ./render/clickhouse/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: backend-app-env
      - fromGroup: clickhouse-credentials
    disk:
      name: data
      mountPath: /var/lib/clickhouse
      sizeGB: 10
  - type: pserv
    name: temporal
    autoDeploy: false
    env: docker
    dockerfilePath: ./render/temporal/server/auto-setup/Dockerfile
    envVars:
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig.yaml
    - key: DB
      value: postgresql
    - key: PORT
      value: 7233
    - key: DBNAME
      fromDatabase:
        name: dittofeed-db
        property: database
    - key: DB_PORT
      fromDatabase:
        name: dittofeed-db
        property: port
    - key: POSTGRES_USER
      fromDatabase:
        name: dittofeed-db
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: dittofeed-db
        property: password
    - key: POSTGRES_SEEDS
      fromDatabase:
        name: dittofeed-db
        property: host
