# A definitive render.yaml blueprint for deploying a single-node Redpanda instance on Render.com.
# This configuration exposes the Pandaproxy (HTTP) API to the internet and the native Kafka API
# to the private network. This is configured for production mode.

services:
  - type: web
    name: redpanda
    runtime: image
    image:
      url: docker.redpanda.com/redpandadata/redpanda:latest
    plan: standard
    region: oregon
    dockerCommand: |
      /bin/sh -c "RP_BOOTSTRAP_USER=\"$USER:$PASSWORD\" /usr/bin/rpk redpanda start \
        --smp 1 --memory 1.5G \
        --kafka-addr internal://0.0.0.0:9092 \
        --advertise-kafka-addr internal://$INTERNAL:9092,external://$EXTERNAL:9093 \
        --pandaproxy-addr external://0.0.0.0:8082 \
        --advertise-pandaproxy-addr external://$RENDER_EXTERNAL_URL \
        --schema-registry-addr external_sr://0.0.0.0:8081 \
        --rpc-addr 0.0.0.0:33145 \
        --advertise-rpc-addr $RENDER_INTERNAL_HOSTNAME:33145 \
        --set redpanda.enable_sasl=true \
        --set redpanda.superusers='[\"$USER\"]' \
        --set redpanda.pandaproxy_api_enable_basic_auth=true \
        --set redpanda.admin_api_enable_basic_auth=true \
        --set redpanda.schema_registry_api_enable_basic_auth=true"

    envVars:
      - key: PORT
        value: "8082"
      - key: USER
        sync: false
      - key: PASSWORD
        sync: false

    disk:
      name: redpanda-data
      mountPath: /var/lib/redpanda/data
      sizeGB: 10

    healthCheckPath: /status/ready
