#!/bin/bash
# Fix for Coolify environment variable configuration

echo "==========================================="
echo "🔧 COOLIFY ENVIRONMENT VARIABLE FIX"
echo "==========================================="
echo ""
echo "❌ PROBLEM IDENTIFIED:"
echo "Your DATABASE_URL value includes 'DATABASE_URL=' prefix"
echo "Current (WRONG): DATABASE_URL=postgresql://..."
echo ""
echo "✅ CORRECT FORMAT IN COOLIFY:"
echo "==========================================="
echo ""
echo "In Coolify Environment Variables, set:"
echo ""
echo "Key: DATABASE_URL"
echo "Value: postgresql://dittofeed:AXRH%2Bft7pHxNF%2FaM2m6P0g%3D%3D@postgres:5432/dittofeed"
echo ""
echo "⚠️  IMPORTANT: The VALUE field should NOT include 'DATABASE_URL='"
echo "Just the URL itself!"
echo ""
echo "==========================================="
echo "🔄 ALTERNATIVE: Use Simple Password"
echo "==========================================="
echo ""
echo "To avoid encoding issues, use a password without special chars:"
echo ""
NEW_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-24)
echo "1. Set these in Coolify Environment Variables:"
echo ""
echo "   POSTGRES_PASSWORD"
echo "   Value: $NEW_PASSWORD"
echo ""
echo "   DATABASE_URL"
echo "   Value: postgresql://dittofeed:${NEW_PASSWORD}@postgres:5432/dittofeed"
echo ""
echo "2. IMPORTANT: Clear the postgres volume first:"
echo "   - Stop the deployment in Coolify"
echo "   - SSH to server and run: docker volume rm <project>_postgres_data"
echo "   - Redeploy in Coolify"
echo ""
echo "==========================================="
echo "📋 COMPLETE ENVIRONMENT VARIABLES"
echo "==========================================="
echo ""
echo "Ensure ALL these are set in Coolify (without the KEY= prefix in values):"
echo ""
echo "NODE_ENV=production"
echo "AUTH_MODE=multi-tenant"
echo "JWT_SECRET=$(openssl rand -base64 32)"
echo "SECRET_KEY=$(openssl rand -base64 32)"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "POSTGRES_PASSWORD=$NEW_PASSWORD"
echo "DATABASE_URL=postgresql://dittofeed:${NEW_PASSWORD}@postgres:5432/dittofeed"
echo "REDIS_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/")"
echo "API_BASE_URL=https://api.com.caramelme.com"
echo "DASHBOARD_URL=https://dashboard.com.caramelme.com"
echo "NEXTAUTH_URL=https://dashboard.com.caramelme.com"
echo "CORS_ORIGIN=https://dashboard.com.caramelme.com"
echo "BOOTSTRAP_WORKSPACE_NAME=Default"
echo "BOOTSTRAP_WORKSPACE_ADMIN_EMAIL=admin@example.com"
echo "CF_TUNNEL_TOKEN=<your-tunnel-token>"
echo ""